session:
  path: session/
  expired: 1800
  timezone: 8
  file_name: "{server_code}-{account_name}-{server_env}.session"


.template:
  x19_default_api: &x19_default_api
    authentication_update: { encrypt_body_type: 1 }
    login_otp:             { encrypt_body_type: 0 }
    authentication_otp:    { encrypt_body_type: 1 }

  g79_default_api: &g79_default_api
    authentication_update: { encrypt_body_type: 2 }
    pe_authentication:
      encrypt_body_type: 4
      extra_param:
        sign_sp: 3
        sign_tr: 9
  
  sa_data_mumu_android: &sa_data_mumu_android
    app_channel: netease
    core_num: 
    cpu_digit: 64
    cpu_hz: 
    cpu_name: 
    device_model: 
    first_udid: 
    network: CHANNEL_UNKNOW
    os_name: android
    os_ver: 
    ram: 
    rom: 
    root: 
    udid: 

  sa_data_vm_win: &sa_data_vm_win 
    core_num: 
    cpu_name: 
    device_height: 
    device_width: 
    first_udid: 
    udid: 

client:
  android:
    type: "pe"
    config: 
      engine_version: 3.7.15.288131
      engine_hash: 0fb7b528b222a7a44a10b08e994c786e
      patch_version: 3.7.37.290123
      patch_hash: f08b83065052e2ccd3ca2defcb43c8c7
      pay_channel: dashen_cloudgame
      # sign_hash: 2b3e7ca013bb30a74d822579860c042b
    sa_data: *sa_data_mumu_android
  android_tech:
    type: "pe"
    config: 
      engine_version: 3.200.100.279901
      engine_hash: 883e42b9df0bf93be5f5345fae6bcefa
      patch_version: 3.200.104.280674
      patch_hash: f000ab0922db96f0ce87d49ea0a74c83
      pay_channel: dashen_cloudgame
      # sign_hash: 2b3e7ca013bb30a74d822579860c042b
    sa_data:
      <<: *sa_data_mumu_android
      cpu_name: placeholder
      ram: 8351973376
  pc_cocos:
    type: "pe"
    config:
      engine_version: 3.7.40.290695
      engine_hash: 74b9ba9a2454db6f694fbfcf1f6faf5d
      patch_version: 3.7.41.290704
      patch_hash: f86bf1f9830f621afb7d7f65b428ae30
      pay_channel: netease
      # sign_hash: 2b3e7ca013bb30a74d822579860c042b
    sa_data: *sa_data_vm_win
  pc_cocos_tech:
    type: "pe"
    config:
      engine_version: 3.5.100.279203
      engine_hash: pc_cocos
      patch_version: 3.5.100.279203
      patch_hash: d41d8cd98f00b204e9800998ecf8427e
      pay_channel: netease
      # sign_hash: 2b3e7ca013bb30a74d822579860c042b
    sa_data: *sa_data_vm_win
  pc_java:
    type: "pc"
    config:
      version: 1.15.18.46492
    sa_data: *sa_data_vm_win

account:
  phone: 
    access_token: 
    deviceid: 
    get_access_token: 
    ip: 
    sdkuid: 
    sessionid: 
    udid: 

server:
  x19:
    adr: 
      serverlist_url: https://x19.update.netease.com/serverlist/adr.json
      api_config: *x19_default_api
      api_host_flag: 0
    expr: 
      serverlist_url: https://x19.update.netease.com/serverlist/experience.0.4.json
      api_config: *x19_default_api
      api_host_flag: 1
    gaiya: 
      serverlist_url: https://x19.update.netease.com/serverlist/gaiya.json
      api_config: *x19_default_api
      api_host_flag: 0
    moyinglong: 
      serverlist_url: https://x19.update.netease.com/serverlist/moyinglong.json
      api_config: *x19_default_api
      api_host_flag: 0
    obt: 
      serverlist_url: https://x19.update.netease.com/serverlist/release.json
      api_config: *x19_default_api
      api_host_flag: 0
    qa: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa.0.4.json
      api_config: *x19_default_api
      api_host_flag: 0
    qa3: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa3_jxsl.0.4.json
      api_config: *x19_default_api
      api_host_flag: 0
    qa4: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa4_season.0.4.json
      api_config: *x19_default_api
      api_host_flag: 0
    sim: 
      serverlist_url: https://x19.update.netease.com/serverlist/sim_gray.json
      api_config: *x19_default_api
      api_host_flag: 2
    stress: 
      serverlist_url: https://x19.update.netease.com/serverlist/stress.json
      api_config: *x19_default_api
      api_host_flag: 0
    taitan: 
      serverlist_url: https://x19.update.netease.com/serverlist/taitan.json
      api_config: *x19_default_api
      api_host_flag: 0
  g79:
    adr: 
      serverlist_url: https://g79.update.netease.com/serverlist/adr_review_forever2.json
      api_config: *g79_default_api
      api_host_flag: 0
    expr: 
      serverlist_url: https://g79.update.netease.com/serverlist/expr_release.json
      api_config: *g79_default_api
      api_host_flag: 0
    expr1: 
      serverlist_url: https://g79.update.netease.com/serverlist/expr1_release.json
      api_config: *g79_default_api
      api_host_flag: 0
    gaiya: 
      serverlist_url: https://g79.update.netease.com/serverlist/gaiya.json
      api_config: *g79_default_api
      api_host_flag: 0
    ios: 
      serverlist_url: https://g79.update.netease.com/serverlist/ios_review_forever.json
      api_config: *g79_default_api
      api_host_flag: 0
    moyinglong: 
      serverlist_url: https://g79.update.netease.com/serverlist/moyinglong.json
      api_config: *g79_default_api
      api_host_flag: 0
    obt: 
      serverlist_url: https://g79.update.netease.com/serverlist/release.gray.json
      api_config: *g79_default_api
      api_host_flag: 0
    qa: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa.0.1.json
      api_config: *g79_default_api
      api_host_flag: 0
    qa3: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa3_jxsl.0.1.json
      api_config: *g79_default_api
      api_host_flag: 0
    qa4: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa4_season.0.1.json
      api_config: *g79_default_api
      api_host_flag: 0
    sim: 
      serverlist_url: https://g79.update.netease.com/serverlist/sim.0.2.json
      api_config: *g79_default_api
      api_host_flag: 0
    stress: 
      serverlist_url: https://g79.update.netease.com/serverlist/stress.0.1.json
      api_config: *g79_default_api
      api_host_flag: 0
    taitan: 
      serverlist_url: https://g79.update.netease.com/serverlist/taitan.json
      api_config: *g79_default_api
      api_host_flag: 0
    tech: 
      serverlist_url: https://g79.update.netease.com/serverlist/tech.0.2.json
      api_config: 
        <<: *g79_default_api
        pe_authentication:
          encrypt_body_type: 4
          extra_param:
            sign_sp: 1
            sign_tr: 8
      api_host_flag: 0
    tesm: 
      serverlist_url: https://g79.update.netease.com/serverlist/tesm.0.2.json
      api_config: *g79_default_api
      api_host_flag: 0
