session:
  path: session/
  expired: 1800
  timezone: 0
  file_name: "{server_code}_{server_env}.session"

client:
  android:
    engine_version: 3.7.15.288131
    engine_hash: 0fb7b528b222a7a44a10b08e994c786e
    patch_version: 3.7.36.289626
    patch_hash: 767f11d6b1d70cac0694477ffcee2c99
    pay_channel: dashen_cloudgame
    # sign_hash: 2b3e7ca013bb30a74d822579860c042b
  pc_cocos:
    engine_version: 3.7.36.289473
    engine_hash: 63ced534eead6be986a3f781bfd74317
    patch_version: 3.7.37.289628
    patch_hash: 583f68793af1bafee193414a4aefa517
    pay_channel: netease
    # sign_hash: 2b3e7ca013bb30a74d822579860c042b
  pc:
    version: 1.15.18.46492

sa_data:
  app_channel: 
  core_num: 
  cpu_digit: 
  cpu_hz: 
  cpu_name: 
  device_model: 
  first_udid: 
  network: 
  os_name: 
  os_ver: 
  ram: 
  rom: 
  root: 
  udid: 

sauth:
  access_token: 
  deviceid: 
  get_access_token: 
  ip: 
  login_channel: 
  sdkuid: 
  sessionid: 
  udid: 

server:
  x19:
    adr: 
      serverlist_url: https://x19.update.netease.com/serverlist/adr.json
      auth_enc_type: 1
      api_host_flag: 0
    expr: 
      serverlist_url: https://x19.update.netease.com/serverlist/experience.0.4.json
      auth_enc_type: 1
      api_host_flag: 1
    gaiya: 
      serverlist_url: https://x19.update.netease.com/serverlist/gaiya.json
      auth_enc_type: 1
      api_host_flag: 0
    moyinglong: 
      serverlist_url: https://x19.update.netease.com/serverlist/moyinglong.json
      auth_enc_type: 1
      api_host_flag: 0
    obt: 
      serverlist_url: https://x19.update.netease.com/serverlist/release.json
      auth_enc_type: 1
      api_host_flag: 0
    qa: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa.0.4.json
      auth_enc_type: 1
      api_host_flag: 0
    qa3: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa3_jxsl.0.4.json
      auth_enc_type: 1
      api_host_flag: 0
    qa4: 
      serverlist_url: https://x19.update.netease.com/serverlist/qa4_season.0.4.json
      auth_enc_type: 1
      api_host_flag: 0
    sim: 
      serverlist_url: https://x19.update.netease.com/serverlist/sim_gray.json
      auth_enc_type: 1
      api_host_flag: 2
    stress: 
      serverlist_url: https://x19.update.netease.com/serverlist/stress.json
      auth_enc_type: 1
      api_host_flag: 0
    taitan: 
      serverlist_url: https://x19.update.netease.com/serverlist/taitan.json
      auth_enc_type: 1
      api_host_flag: 0
  g79:
    adr: 
      serverlist_url: https://g79.update.netease.com/serverlist/adr_review_forever2.json
      auth_enc_type: 4
      api_host_flag: 0
    expr: 
      serverlist_url: https://g79.update.netease.com/serverlist/expr_release.json
      auth_enc_type: 4
      api_host_flag: 0
    expr1: 
      serverlist_url: https://g79.update.netease.com/serverlist/expr1_release.json
      auth_enc_type: 4
      api_host_flag: 0
    gaiya: 
      serverlist_url: https://g79.update.netease.com/serverlist/gaiya.json
      auth_enc_type: 4
      api_host_flag: 0
    ios: 
      serverlist_url: https://g79.update.netease.com/serverlist/ios_review_forever.json
      auth_enc_type: 0
      api_host_flag: 0
    moyinglong: 
      serverlist_url: https://g79.update.netease.com/serverlist/moyinglong.json
      auth_enc_type: 4
      api_host_flag: 0
    obt: 
      serverlist_url: https://g79.update.netease.com/serverlist/release.gray.json
      auth_enc_type: 4
      api_host_flag: 0
    qa: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa.0.1.json
      auth_enc_type: 4
      api_host_flag: 0
    qa3: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa3_jxsl.0.1.json
      auth_enc_type: 4
      api_host_flag: 0
    qa4: 
      serverlist_url: https://g79.update.netease.com/serverlist/qa4_season.0.1.json
      auth_enc_type: 4
      api_host_flag: 0
    sim: 
      serverlist_url: https://g79.update.netease.com/serverlist/sim.0.2.json
      auth_enc_type: 4
      api_host_flag: 0
    stress: 
      serverlist_url: https://g79.update.netease.com/serverlist/stress.0.1.json
      auth_enc_type: 4
      api_host_flag: 0
    taitan: 
      serverlist_url: https://g79.update.netease.com/serverlist/taitan.json
      auth_enc_type: 4
      api_host_flag: 0
    tech: 
      serverlist_url: https://g79.update.netease.com/serverlist/tech.0.2.json
      auth_enc_type: 4
      api_host_flag: 0
    tesm: 
      serverlist_url: https://g79.update.netease.com/serverlist/tesm.0.2.json
      auth_enc_type: 4
      api_host_flag: 0
